name       : grsync
version    : 1.3.0
release    : 3
source     :
    - http://www.opbyte.it/release/grsync-1.3.0.tar.gz : b7c7c6a62e05302d8317c38741e7d71ef9ab4639ee5bff2622a383b2043a35fc
license    : GPL-2.0-or-later
component  : network.util
summary    : Grsync is used to synchronize folders, files and make backups.
description: |
    Grsync is used to synchronize folders, files and make backups.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - rsync
rundeps    :
    - rsync
setup      : |
    %configure --disable-unity
build      : |
    %make
install    : |
    %make_install
