name       : grsync
version    : 1.2.5
release    : 1
source     :
    - http://www.opbyte.it/release/grsync-1.2.5.tar.gz : 4f1443154f7c85ca7b0e93d5fea438e2709776005e7cfc97da89f4899b1c12e5
license    : GPL-2.0
summary    : Grsync is used to synchronize folders, files and make backups.
description: |
    Grsync is used to synchronize folders, files and make backups.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - rsync
rundeps :
    - rsync
setup      : |
    %configure --disable-unity
build      : |
    %make
install    : |
    %make_install
