name       : grsync
version    : 1.2.6
release    : 2
source     :
    - http://www.opbyte.it/release/grsync-1.2.6.tar.gz : 66d5acea5e6767d6ed2082e1c6e250fe809cb1e797cbbee5c8e8a2d28a895619
license    : GPL-2.0
component  : network.util
summary    : Grsync is used to synchronize folders, files and make backups.
description: |
    Grsync is used to synchronize folders, files and make backups.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - rsync
rundeps :
    - rsync
setup      : |
    %configure --disable-unity
build      : |
    %make
install    : |
    %make_install
